CREATE TABLE question_banks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    subject_id UUID NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    class_id UUID NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    stream_id UUID REFERENCES streams(id) ON DELETE SET NULL,
    session_id UUID REFERENCES academic_sessions(id) ON DELETE SET NULL,
    term_id UUID REFERENCES terms(id) ON DELETE SET NULL,
    question_text TEXT NOT NULL,
    question_type VARCHAR(20) NOT NULL CHECK (question_type IN ('multiple_choice', 'true_false', 'theory')),
    option_a TEXT,
    option_b TEXT,
    option_c TEXT,
    option_d TEXT,
    correct_option VARCHAR(5) CHECK (correct_option IN ('a', 'b', 'c', 'd', 'true', 'false')),
    explanation TEXT,
    marks NUMERIC(5,2) DEFAULT 1,
    difficulty_level VARCHAR(10) DEFAULT 'medium' CHECK (difficulty_level IN ('easy', 'medium', 'hard')),
    is_active BOOLEAN DEFAULT TRUE,
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE cbt_exams (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    exam_title VARCHAR(255) NOT NULL,
    subject_id UUID NOT NULL REFERENCES subjects(id) ON DELETE CASCADE,
    class_id UUID NOT NULL REFERENCES classes(id) ON DELETE CASCADE,
    stream_id UUID REFERENCES streams(id) ON DELETE SET NULL,
    session_id UUID NOT NULL REFERENCES academic_sessions(id) ON DELETE CASCADE,
    term_id UUID NOT NULL REFERENCES terms(id) ON DELETE CASCADE,
    exam_type VARCHAR(20) NOT NULL CHECK (exam_type IN ('ca', 'exam', 'mock')),
    total_questions INTEGER NOT NULL DEFAULT 40,
    total_marks NUMERIC(7,2) NOT NULL,
    duration_minutes INTEGER NOT NULL DEFAULT 60,
    pass_mark NUMERIC(5,2) DEFAULT 40,
    shuffle_questions BOOLEAN DEFAULT TRUE,
    shuffle_options BOOLEAN DEFAULT TRUE,
    show_result_immediately BOOLEAN DEFAULT FALSE,
    allow_review BOOLEAN DEFAULT TRUE,
    instructions TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE cbt_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    exam_id UUID NOT NULL REFERENCES cbt_exams(id) ON DELETE CASCADE,
    session_name VARCHAR(255) NOT NULL,
    scheduled_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    venue VARCHAR(255),
    max_students INTEGER,
    is_open BOOLEAN DEFAULT FALSE,
    is_completed BOOLEAN DEFAULT FALSE,
    opened_by UUID REFERENCES users(id) ON DELETE SET NULL,
    opened_at TIMESTAMP,
    closed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE cbt_results (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    cbt_session_id UUID NOT NULL REFERENCES cbt_sessions(id) ON DELETE CASCADE,
    exam_id UUID NOT NULL REFERENCES cbt_exams(id) ON DELETE CASCADE,
    student_id UUID NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    answers JSONB,
    total_questions INTEGER,
    questions_answered INTEGER DEFAULT 0,
    correct_answers INTEGER DEFAULT 0,
    wrong_answers INTEGER DEFAULT 0,
    skipped_answers INTEGER DEFAULT 0,
    score_obtained NUMERIC(7,2) DEFAULT 0,
    total_marks NUMERIC(7,2),
    percentage NUMERIC(5,2) DEFAULT 0,
    time_taken_minutes INTEGER,
    started_at TIMESTAMP,
    submitted_at TIMESTAMP,
    submission_type VARCHAR(20) DEFAULT 'manual' CHECK (submission_type IN ('manual', 'auto', 'forced')),
    is_graded BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(cbt_session_id, student_id)
);
CREATE TABLE public_exam_questions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    exam_body VARCHAR(20) NOT NULL CHECK (exam_body IN ('WAEC', 'UTME', 'NECO', 'BECE')),
    subject_name VARCHAR(100) NOT NULL,
    year INTEGER,
    question_text TEXT NOT NULL,
    question_type VARCHAR(20) DEFAULT 'multiple_choice' CHECK (question_type IN ('multiple_choice', 'true_false')),
    option_a TEXT,
    option_b TEXT,
    option_c TEXT,
    option_d TEXT,
    correct_option VARCHAR(5) CHECK (correct_option IN ('a', 'b', 'c', 'd', 'true', 'false')),
    explanation TEXT,
    topic VARCHAR(255),
    difficulty_level VARCHAR(10) DEFAULT 'medium' CHECK (difficulty_level IN ('easy', 'medium', 'hard')),
    is_active BOOLEAN DEFAULT TRUE,
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE public_exam_attempts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    attempt_reference VARCHAR(100) UNIQUE NOT NULL,
    exam_body VARCHAR(20) NOT NULL CHECK (exam_body IN ('WAEC', 'UTME', 'NECO', 'BECE')),
    subject_name VARCHAR(100) NOT NULL,
    candidate_name VARCHAR(255),
    answers JSONB,
    total_questions INTEGER,
    questions_answered INTEGER DEFAULT 0,
    correct_answers INTEGER DEFAULT 0,
    wrong_answers INTEGER DEFAULT 0,
    score_obtained NUMERIC(7,2) DEFAULT 0,
    percentage NUMERIC(5,2) DEFAULT 0,
    time_taken_minutes INTEGER,
    started_at TIMESTAMP DEFAULT NOW(),
    submitted_at TIMESTAMP,
    ip_address VARCHAR(50),
    device_info TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);