CREATE TABLE library_books (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255),
    isbn VARCHAR(50) UNIQUE,
    publisher VARCHAR(255),
    publication_year INTEGER,
    edition VARCHAR(50),
    category VARCHAR(100),
    subject_id UUID REFERENCES subjects(id) ON DELETE SET NULL,
    class_level VARCHAR(10) CHECK (class_level IN ('JSS', 'SSS', 'Both', 'General')),
    description TEXT,
    cover_image_url TEXT,
    file_url TEXT,
    book_type VARCHAR(20) NOT NULL CHECK (book_type IN ('physical', 'ebook', 'both')),
    total_copies INTEGER DEFAULT 1 CHECK (total_copies >= 0),
    available_copies INTEGER DEFAULT 1 CHECK (available_copies >= 0),
    is_active BOOLEAN DEFAULT TRUE,
    added_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);
CREATE TABLE book_borrowings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    book_id UUID NOT NULL REFERENCES library_books(id) ON DELETE CASCADE,
    borrower_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    borrower_type VARCHAR(20) NOT NULL CHECK (borrower_type IN ('student', 'teacher')),
    borrowed_date DATE NOT NULL DEFAULT CURRENT_DATE,
    due_date DATE NOT NULL,
    returned_date DATE,
    borrow_status VARCHAR(20) DEFAULT 'borrowed' CHECK (borrow_status IN ('borrowed', 'returned', 'overdue', 'lost')),
    issued_by UUID REFERENCES users(id) ON DELETE SET NULL,
    received_by UUID REFERENCES users(id) ON DELETE SET NULL,
    fine_amount NUMERIC(10,2) DEFAULT 0,
    fine_paid BOOLEAN DEFAULT FALSE,
    remarks TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);